import mongoose from "mongoose";

const jobSchema = new mongoose.Schema({
    title: {
        type:String,
        required:true
    },
    jobType:{
        type:String,
        required:true,
        enum:['Full-time',"Intern"]
    },
    companyName:{
        type:String,
        required:true
    },
    location:{
        type:String,
        required:true
    },
    description:{
        type:String,
    },
    responsibilities:{
        type:String,
        required:true
    },
    qualifications:{
        type:String,
        required:true
    },
    openings:{
        type:Number,
        required:true,
    },
    experience:{
        type:String,
        required:true,
    },
    offers:{
        type:String
    },
    salary:{
        type:String,
        required:true
    },
    personalWebSite:{
        title:String,
        url:String
    },
    jobNiche:{
        type:String,
        default:true
    },
    notificationSent:{
        type:Boolean,
        default:false
    },
    hiringProcess:{
        type:String,
        required:true
    },
    jobPostedOn:{
        type:Date,
        default:Date.now
    },
    postedBy:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true
    }
});
export const Job = mongoose.model("Job",jobSchema);